services:
  - type: web
    name: kisaan-mitra
    runtime: python
    pythonVersion: 3.11.8
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
